@startuml
Class ToDoTemplateController{
EnterTaskTexField
EnterDescriptionTextField
SaveListButtonClicked
HomeButtonClicked
NameListTextField
AddTaskTextField
AddDescriptionTextField
AddDueDateTextField
AddTaskButtonClicked
DeleteButtonClicked
}

Class TaskModel{
CheckBox CheckColumn
DatePicker DueDateColumn
String TaskName
String Description
}

Class WelcomeController{
EditButtonClicked
CreateListButtonClicked
UploadListButtonClicked
DeleteListButtonClicked
EditListButtonClicked
}

Class CreateListController{
HomeButtonClicked
CreateListEnterButtonClicked
}




Class UploadListController{
HomeButtonClicked
UploadListEnterButtonClicked
}
Class ExecuteGUI{
start()
main()
}
ExecuteGUI-->UploadListController
ExecuteGUI-->CreateListController
ExecuteGUI-->ToDoTemplateController
ExecuteGUI-->WelcomeController

TaskModel--ToDoTemplateController






@enduml