@startuml
Class ToDoTemplateController{
EnterTaskTexField
EnterDescriptionTextField
SaveListButtonClicked()
UploadListButtonClicked()
HomeButtonClicked()
NameListTextField
CheckBox Checkoff
AddTaskTextField()
AddDescriptionTextField
AddDueDateTextField
AddTaskButtonClicked()
DeleteButtonClicked()
}

Class TaskModel{
CheckBox CheckColumn
DatePicker DueDateColumn
String TaskName
String Description
}

Class WelcomeController{
CreateListEnterButtonClicked
}

Class CreateListController{
String taskTitle
HomeButtonClicked
CreateListEnterButtonClicked()
}


Class ExecuteGUI{
start()
main()
}

WelcomeController-->CreateListController
CreateListController-->ToDoTemplateController
ExecuteGUI-->WelcomeController

TaskModel--ToDoTemplateController






@enduml
